class TestMarry:
    def test_run_marry(self):
        import marry
        # raise Exception("this is a test failure")
